######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 2 06:57:51 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cropbag.h
SOURCES += cropbag.cpp main.cpp
